services:
  - type: web
    name: nepali-sentiment-api
    env: python
    pythonVersion: 3.11.9
    plan: free
    buildCommand: python -m pip install --upgrade pip && pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
